version: 2
updates:
  - package-ecosystem: gomod
    directory: "/src/"
    schedule:
      interval: monthly
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
          - "github.com/open-telemetry/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
