version: 2
project_name: "sacloud-otel-collector"
before:
  hooks:
    - sh -c 'cd cmd/sacloud-otel-collector && go mod download'
builds:
  - env:
      - CGO_ENABLED=0
    dir: ./cmd/sacloud-otel-collector
    binary: sacloud-otel-collector
    goos:
      - linux
    goarch:
      - amd64
      - arm64
release:
  use_existing_draft: true
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - package_name: sacloud-otel-collector
    vendor: SAKURA Internet Inc.
    homepage: https://github.com/sacloud/sacloud-otel-collector
    description: |-
      OpenTelemetry collector for SAKURA Cloud
    license: "Apache 2.0"
    formats:
      - deb
      - rpm
    maintainer: SAKURA internet Inc. <support@sakura.ad.jp>
    contents:
      - src: ./packages/config.yaml
        dst: /etc/sacloud-otel-collector/config.yaml
      - src: ./packages/sacloud-otel-collector.env
        dst: /etc/default/sacloud-otel-collector
      - src: ./packages/sacloud-otel-collector.service
        dst: /etc/systemd/system/sacloud-otel-collector.service
