version: 2
project_name: "sacloud-otel-collector"
before:
  hooks:
    - sh -c 'cd src && go mod download'
builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    dir: ./src
    binary: sacloud-otel-collector
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
