// Command readmegen generates the component tables in README.md from
// builder-config.yaml, so that documentation links always point to the
// component versions bundled in the collector.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path"
	"strings"
	"text/template"

	"go.yaml.in/yaml/v3"
)

const (
	beginMarker = "<!-- BEGIN COMPONENTS: generated by tools/readmegen from builder-config.yaml. DO NOT EDIT. -->"
	endMarker   = "<!-- END COMPONENTS -->"
)

// vanityRepos maps vanity import path prefixes to GitHub repositories.
var vanityRepos = map[string]string{
	"go.opentelemetry.io/collector": "open-telemetry/opentelemetry-collector",
}

// Module is a component entry in builder-config.yaml.
// Type, Description and Doc are ignored by ocb and used only by readmegen.
type Module struct {
	GoMod       string `yaml:"gomod"`
	Path        string `yaml:"path"`
	Type        string `yaml:"type"`
	Description string `yaml:"description"`
	Doc         string `yaml:"doc"`
}

type BuilderConfig struct {
	Receivers  []Module `yaml:"receivers"`
	Processors []Module `yaml:"processors"`
	Exporters  []Module `yaml:"exporters"`
	Connectors []Module `yaml:"connectors"`
	Extensions []Module `yaml:"extensions"`
}

type Row struct {
	Type        string
	Description string
	DocURL      string
}

type Section struct {
	Title string
	Rows  []Row
}

var tableTemplate = template.Must(template.New("table").Funcs(template.FuncMap{
	"cell": func(s string) string { return strings.ReplaceAll(s, "|", `\|`) },
}).Parse(`{{ range $i, $s := . }}{{ if $i }}
{{ end }}### {{ $s.Title }}

| Component | Description | Documentation |
|-----------|-------------|---------------|
{{ range $s.Rows }}| {{ cell .Type }} | {{ cell .Description }} | [Documentation]({{ .DocURL }}) |
{{ end }}{{ end }}`))

func main() {
	configPath := flag.String("config", "builder-config.yaml", "path to builder-config.yaml")
	readmePath := flag.String("readme", "README.md", "path to README.md")
	check := flag.Bool("check", false, "exit with an error if README.md is out of date instead of updating it")
	flag.Parse()

	if err := run(*configPath, *readmePath, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(configPath, readmePath string, check bool) error {
	b, err := os.ReadFile(configPath)
	if err != nil {
		return err
	}
	var cfg BuilderConfig
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return fmt.Errorf("%s: %w", configPath, err)
	}
	table, err := renderTables(&cfg)
	if err != nil {
		return fmt.Errorf("%s: %w", configPath, err)
	}

	orig, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	updated, err := replaceBetweenMarkers(string(orig), table)
	if err != nil {
		return fmt.Errorf("%s: %w", readmePath, err)
	}
	if updated == string(orig) {
		return nil
	}
	if check {
		return fmt.Errorf("%s: component tables are out of date. Run `make readme`", readmePath)
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		return err
	}
	fmt.Printf("updated %s\n", readmePath)
	return nil
}

func renderTables(cfg *BuilderConfig) (string, error) {
	var sections []Section
	var errs []error
	for _, s := range []struct {
		title   string
		modules []Module
	}{
		{"Receivers", cfg.Receivers},
		{"Processors", cfg.Processors},
		{"Exporters", cfg.Exporters},
		{"Connectors", cfg.Connectors},
		{"Extensions", cfg.Extensions},
	} {
		if len(s.modules) == 0 {
			continue
		}
		sec := Section{Title: s.title}
		for _, m := range s.modules {
			row, err := m.row()
			if err != nil {
				errs = append(errs, err)
				continue
			}
			sec.Rows = append(sec.Rows, row)
		}
		sections = append(sections, sec)
	}
	if err := errors.Join(errs...); err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tableTemplate.Execute(&buf, sections); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func (m Module) row() (Row, error) {
	if m.Type == "" || m.Description == "" {
		return Row{}, fmt.Errorf("%s: type and description are required", m.GoMod)
	}
	url, err := m.docURL()
	if err != nil {
		return Row{}, err
	}
	return Row{Type: m.Type, Description: m.Description, DocURL: url}, nil
}

func (m Module) docURL() (string, error) {
	if m.Doc != "" {
		return m.Doc, nil
	}
	if m.Path != "" {
		// Local module in this repository.
		return path.Join(m.Path, "README.md"), nil
	}
	mod, version, ok := strings.Cut(m.GoMod, " ")
	if !ok {
		return "", fmt.Errorf("%s: version is missing", m.GoMod)
	}
	repo, sub, err := githubRepo(mod)
	if err != nil {
		return "", err
	}
	// Go modules in subdirectories are tagged as <subdir>/<version>.
	return fmt.Sprintf("https://github.com/%s/tree/%s/%s/%s", repo, sub, strings.TrimSpace(version), sub), nil
}

// githubRepo splits a module path into a GitHub repository and a subdirectory.
func githubRepo(mod string) (repo, sub string, err error) {
	for prefix, r := range vanityRepos {
		if s, ok := strings.CutPrefix(mod, prefix+"/"); ok {
			return r, s, nil
		}
	}
	if s, ok := strings.CutPrefix(mod, "github.com/"); ok {
		parts := strings.SplitN(s, "/", 3)
		if len(parts) == 3 {
			return parts[0] + "/" + parts[1], parts[2], nil
		}
	}
	return "", "", fmt.Errorf("%s: cannot map module to a GitHub URL; set doc explicitly", mod)
}

func replaceBetweenMarkers(content, generated string) (string, error) {
	before, rest, ok := strings.Cut(content, beginMarker)
	if !ok {
		return "", fmt.Errorf("marker %q not found", beginMarker)
	}
	_, after, ok := strings.Cut(rest, endMarker)
	if !ok {
		return "", fmt.Errorf("marker %q not found", endMarker)
	}
	return before + beginMarker + "\n\n" + generated + "\n" + endMarker + after, nil
}
