package selfmetricsreceiver

import (
	"context"
	"fmt"
	"regexp"

	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/consumer"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

// scrapeJobName is used as the Prometheus job name, which becomes the
// service.name resource attribute of the collected metrics.
const scrapeJobName = "sacloud-otel-collector"

// droppedMetricNames matches the synthetic metrics generated by the Prometheus
// scrape loop, which are meaningless when the collector scrapes itself: `up`
// is always 1 (if the collector were down it could not send anything), and the
// scrape_* statistics only describe the self-scrape. These series cannot be
// removed with metric_relabel_configs because Prometheus does not apply metric
// relabeling to automatically generated series, so they are filtered out of
// the pipeline data instead.
var droppedMetricNames = regexp.MustCompile(`^(up|scrape_.+)$`)

// newMetricsReceiver creates a new metrics receiver using prometheusreceiver
// configured to scrape the collector's own internal telemetry endpoint.
func newMetricsReceiver(ctx context.Context, set receiver.Settings, cfg *Config, next consumer.Metrics) (receiver.Metrics, error) {
	factory := prometheusreceiver.NewFactory()
	promCfg, err := buildPromConfig(factory, cfg)
	if err != nil {
		return nil, err
	}

	// Create new settings with the correct component type
	promSet := receiver.Settings{
		ID:                component.NewIDWithName(factory.Type(), set.ID.Name()),
		TelemetrySettings: set.TelemetrySettings,
		BuildInfo:         set.BuildInfo,
	}

	return factory.CreateMetrics(ctx, promSet, promCfg, &filteringConsumer{next: next})
}

// buildPromConfig builds the prometheusreceiver config that scrapes the
// collector's own telemetry endpoint.
func buildPromConfig(factory receiver.Factory, cfg *Config) (*prometheusreceiver.Config, error) {
	promCfg, ok := factory.CreateDefaultConfig().(*prometheusreceiver.Config)
	if !ok {
		return nil, fmt.Errorf("failed to cast to prometheusreceiver.Config")
	}

	// Build the scrape config via confmap so that prometheusreceiver's own
	// unmarshaling applies the Prometheus config defaults.
	conf := confmap.NewFromStringMap(map[string]any{
		"config": map[string]any{
			"scrape_configs": []any{
				map[string]any{
					"job_name":        scrapeJobName,
					"scrape_interval": cfg.CollectionInterval.String(),
					"static_configs": []any{
						map[string]any{
							"targets": []any{cfg.Endpoint},
						},
					},
				},
			},
		},
	})
	if err := conf.Unmarshal(promCfg); err != nil {
		return nil, fmt.Errorf("failed to build prometheus receiver config: %w", err)
	}
	return promCfg, nil
}

// filteringConsumer removes the metrics matching droppedMetricNames before
// passing the data to the next consumer.
type filteringConsumer struct {
	next consumer.Metrics
}

func (fc *filteringConsumer) Capabilities() consumer.Capabilities {
	return consumer.Capabilities{MutatesData: true}
}

func (fc *filteringConsumer) ConsumeMetrics(ctx context.Context, md pmetric.Metrics) error {
	rms := md.ResourceMetrics()
	for i := 0; i < rms.Len(); i++ {
		sms := rms.At(i).ScopeMetrics()
		for j := 0; j < sms.Len(); j++ {
			sms.At(j).Metrics().RemoveIf(func(m pmetric.Metric) bool {
				return droppedMetricNames.MatchString(m.Name())
			})
		}
		sms.RemoveIf(func(sm pmetric.ScopeMetrics) bool {
			return sm.Metrics().Len() == 0
		})
	}
	rms.RemoveIf(func(rm pmetric.ResourceMetrics) bool {
		return rm.ScopeMetrics().Len() == 0
	})
	return fc.next.ConsumeMetrics(ctx, md)
}
